name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0'
        include-prerelease: True
    - name: Restore dependencies
      run: dotnet restore ./BlazorBffOpenIDConnect/Server
    - name: Build Blazor template
      run: dotnet build ./BlazorBffOpenIDConnect/Server/BlazorBffOpenIDConnect.Server.csproj --no-restore
