name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0'
        include-prerelease: True
    - name: Restore dependencies
      run: dotnet restore ./content/BlazorBffOpenIDConnect/Server
    - name: Build STS
      run: dotnet build ./content/BlazorBffOpenIDConnect/Server/Blazor.BFF.OpenIDConnect.Server.csproj --no-restore
